A = int(input("Give me the first number: "))
B = int(input("Give me your second number "))
print("Thank you!")
print(f"{A} + {B}", "=", end=' ')
print(A+B)
print(f"{A} - {B}", "=", end=' ')
print(A-B)
print(f"{A} / {B}", "=", end=' ')
print(A/B)
print(f"{A} * {B}", "=", end=' ')
print(A*B)
